apiVersion: v2
name: workshop-test
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: redhat-ws
    repository: "oci://ghcr.io/annakrupnik-dev/helm"
    version: "1.0.5"
    alias: deploy1
  - name: redhat-ws
    repository: "oci://ghcr.io/annakrupnik-dev/helm"
    version: "1.0.5"
    alias: deploy2
version: 1.0.0
appVersion: "1.0.0"