deploy1: 
  ReplicaNumber: 1

  containers:
    containerPort: 8080
    image: 'quay.io/annakrupnik-dev/helllo-world'
    tag: 'chart_v1'
  argocd:
    syncwave:
      deployment: 5
      configmap: 1
  service:
    servicePort: 8080

deploy2: 
  ReplicaNumber: 1

  containers:
    containerPort: 8080
    image: 'quay.io/annakrupnik-dev/helllo-world'
    tag: 'chart_v1'
  argocd:
  syncwave:
     deployment: 10
  service:
    servicePort: 8080
  argocd:
    syncwave: 
      deployment: 5
      configmap: 1