ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/annakrupnik-dev/helllo-world'
  tag: 'chart_v1'

Probes:
  readiness:
    httpGet:
      path: /health/readiness
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    httpGet:
      path: /health/liveness
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
volume:
  mount:
    path: /tmp/html
argocd:
  syncwave: 
    deployment: 5
    configmap: 1
service:
  servicePort: 8080